[project]
name = "2015"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pytest>=8.3.5",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.14",
    "pylint>=3.3.6",
]
